INSERT INTO CUSTOMER (ID, FIRST_NAME, DATE_OF_BIRTH, ADDRESS) values (1, 'Meredith', '1998-07-13', 'Colombo');
INSERT INTO CUSTOMER (ID, FIRST_NAME, DATE_OF_BIRTH, ADDRESS) values (2, 'Joan', '1982-10-29', 'Colombo');
INSERT INTO CUSTOMER (ID, FIRST_NAME, DATE_OF_BIRTH, ADDRESS) values (3, 'Pirathap', '1992-03-15', 'Colombo');
INSERT INTO CUSTOMER (ID, FIRST_NAME, DATE_OF_BIRTH, ADDRESS) values (4, 'SP', '1990-09-30', 'Colombo');
